envVarGroups:
  - name: secrets-prod
    envVars:
      - key: API_HOST_SECRET_KEY
        sync: false 
      - key: IP_KEY_SALT
        sync: false
      - key: USERS_DB_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: webusers-postgres
    postgresMajorVersion: 16
    databaseName: webusers
    plan: free
    ipAllowList: []

services:
  - type: redis
    name: web-redis
    plan: free
    ipAllowList: []

  - type: web
    name: webpredictor-api
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    context: .
    envVars:
      - key: REDIS_URL
        fromService:
          name: web-redis
          type: redis
          property: connectionString
      - key: USERS_DB_URL
        fromDatabase:
          name: webusers-postgres
          property: connectionString
      - fromGroup: secrets-prod
