envVarGroups:
  - name: secrets-prod
    envVars:
      - key: API_HOST_SECRET_KEY
        value: null 
      - key: IP_KEY_SALT
        value: null
      - key: USERS_DB_URL
        value: null
      - key: ADMIN_PASSWORD
        value: null

services:
  - type: redis
    name: web-redis
    plan: free
    ipAllowList: []

  - type: postgres
    name: webusers-postgres
    plan: free
    ipAllowList: []

  - type: web
    name: webpredictor-api
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: REDIS_URL
        fromService:
          name: web-redis
          type: redis
          property: connectionString
      - key: USERS_DB_URL
        fromService:
          name: webusers-postgres
          type: postgres
          property: connectionString
      - fromGroup: secrets-prod
