services:
  - type: redis
    name: redis
    plan: free

  - type: web
    name: webpredictor-api
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: REDIS_URL
        value: redis://redis:6379/0
